### PR TITLE
New docs to write binary files

### PR DESCRIPTION
**Pull request by raphaeldussin**

### CODE REVIEW

**Comment by timothyas** [comment]
Thanks for this Raphael!

**Comment by raphaeldussin** [comment]
@timothyas you're very welcome! trying to add some more examples to the documentation.
If you think of something you'd like to see, let me know!

**Comment by rabernat** [comment]
I noticed that the docstrings on the `write_to_binary` and `rebuild_llc_facets` are not formatted correctly.

https://xmitgcm.readthedocs.io/en/latest/utils.html#xmitgcm.utils.write_to_binary

You need to use numpydoc for all docstrings in order for them to be parsed correctly:
https://numpydoc.readthedocs.io/en/latest/format.html

**Comment by raphaeldussin** [comment]
@rabernat problem fixed

**Pull request merged**
