### PR TITLE
Make dask and mmap mutually exclusive

### LINKED ISSUE #156: local tests failing with "too many open files"
I can no longer run the test suite locally. Tests start failing with "OSError: [Errno 24] Too many open files". @aulemahal found the same problem in #149.

We must not be closing files somewhere.

### PR DESCRIPTION
**Pull request by malmans2**
Closes #156

### CODE REVIEW

**Comment by rabernat** [comment]
Hi @malmans2 - trying to get back to review this as well.

Did you tests pass locally. We are getting quite a few test failures on travis. Any ideas?

**Comment by malmans2** [comment]
Yes, locally using python3.6 the "too many open files problem" is fixed and I didn't get new failures. I don't think that the errors on Travis are due to this PR:

- Python 2.7: the problem should be fixed in Python2.7.16 (https://github.com/conda/conda/issues/9117). When I submitted this PR python 2.7.15 was installed. Re-building the test on Travis should fix it.
- Python 3.6: I think most of the failures are due to #157. I see that only one environment has this error: `numpy.core._exceptions.MemoryError`. I don't think the problem is the python environment/code, but for some reason the machine used had some weird memory limitation.

@rabernat Can you please re-build the tests of this PR? (it seems I can't trigger it).

**Comment by rabernat** [comment]
@malmans2 - I hope you had a great holiday! Thanks for continuing to work on this!

I just restarted the build. I also invited you as an owner on this repo, which I think should give you such privileges on travis.

**Comment by malmans2** [comment]
Thanks! OK, everything related to this PR looks good. Failures are due to #157.
There are also new errors in `test_llcreader` for python3.6 (I can reproduce locally), which I think are due to some change in the latest version of `request`. I'm not very familiar whit it though: Do you know what's causing it?

**Comment by rabernat** [comment]
The llcreader failures are related to an API change in fsspec (see https://github.com/intake/filesystem_spec/issues/123). The headaches never end. 😫

**Pull request merged**
